### ISSUE TITLE
Efficiency, not effectivity

### ISSUE THREAD

**Issue by uzdj** [KirkMcDonald/kirkmcdonald.github.io#114] opened 2018-12-23 02:22 UTC
All visible references to the [Efficiency module](https://wiki.factorio.com/Efficiency_module)s use "effectivity" (its internal name) instead of "efficiency".

**Comment by KirkMcDonald** [comment] 2018-12-24 22:56
I am closing this as a duplicate of #92, as it is a subset of that problem.

**Closed by KirkMcDonald** 2018-12-24 22:56 UTC
