### ISSUE TITLE
[Bug] Cannot Select Advanced Oil Processing

### ISSUE THREAD

**Issue by Sarai91** [KirkMcDonald/kirkmcdonald.github.io#151] opened 2019-06-03 05:08 UTC
The calculations for oil processing in the Factory and Visualize tabs will only show Standard Oil Processing, even if Advanced Oil Processing is selected as the "Primary oil processing recipe" in the Settings tab. Calculations for Coal Liquefaction work as intended.

Steps to reproduce:

1. Select Heavy Oil as the recipe to look up.
2. Select Advanced Oil Processing as the "Primary oil processing recipe" in the Settings Tab:
![Advanced Oil Processing Bug 2](https://user-images.githubusercontent.com/19323146/58777437-20dbda80-8583-11e9-9435-d81608290e11.png)

3. Observe the calculations in the Factory Tab:

![Advanced Oil Processing Bug](https://user-images.githubusercontent.com/19323146/58777366-e4a87a00-8582-11e9-934c-1f462147c9e0.png)

**Comment by Sarai91** [comment] 2019-06-03 05:10
Note: This affects both the 0.16 and 0.17 calculators.

**Comment by RustyBlade64** [comment] 2019-06-05 22:52
Looks like a duplicate of #119

**Comment by KirkMcDonald** [comment] 2019-07-19 18:40
This is indeed a duplicate of #119, with shades of the issue described in #154.

**Closed by KirkMcDonald** 2019-07-19 18:40 UTC
