### ISSUE TITLE
Suggestion: Allow modules/beacons for pumpjacks

### ISSUE THREAD

**Issue by Nucleus24** [KirkMcDonald/kirkmcdonald.github.io#162] opened 2019-07-16 18:19 UTC
Currently, modules and beacons work on miners, but not pumpjacks. It would be safe to assume minimum per-pumpjack output, to simulate steady state conditions.

**Comment by KirkMcDonald** [comment] 2019-07-19 18:20
More generally, the calculator does not model the output rate of pumpjacks at all, due to the amount of variability in a pumpjack's output. This is a duplicate of #52.

**Closed by KirkMcDonald** 2019-07-19 18:20 UTC

**Comment by Nucleus24** [comment] 2019-07-19 20:37
Pumpjacks do have a variable output at the start, but with use every pumpjack will eventually be "drained" and at 20% output. I think that it would be value-added to add this as a feature so that you can know "I need at least X many pumpjacks with the following modules/beacons as inputs".
