### ISSUE TITLE
Oil production not configurable

### ISSUE THREAD

**Issue by TheWerdOfRa** [KirkMcDonald/kirkmcdonald.github.io#106] opened 2018-10-09 20:51 UTC
When calculating how oil is created the calculator seems to only choose coal liquification no matter the options in the settings tab. Not sure if I am making a mistake, but I cannot figure out how to change it to advanced oil processing.

**Comment by KirkMcDonald** [comment] 2018-10-10 06:28
I cannot reproduce this. Do you have an example URL? Or does it happen for you even from a fresh load of the page?

**Comment by TheWerdOfRa** [comment] 2018-10-14 23:57
https://kirkmcdonald.github.io/calc.html#rate=s&min=3&fuel=rocket-fuel&belt=express-transport-belt&dm=p3&db=s3&dbc=8&items=plastic-bar:r:40&modules=plastic-bar:;s3:4

In this URL I am looking to produce 40 plastic per second. I have set the settings tab to the advanced oil processing, but this displays the coal liquification recipe to me (see photo). I am currently using Chrome. I tried to use this tool in IE and it did not load. I turned my ad blocker off and reloaded with no change in performance.

![image](https://user-images.githubusercontent.com/17488364/46923775-e1bd4100-d014-11e8-9a54-aae41d3f0fa3.png)

![image](https://user-images.githubusercontent.com/17488364/46923788-06191d80-d015-11e8-8e72-c2ae964b0e89.png)

**Comment by TheWerdOfRa** [comment] 2018-10-15 00:02
For clarity. I turned the ad blocker off in Chrome. I have no plugins on IE, completely untouched from install (but fully updated).

**Comment by KirkMcDonald** [comment] 2018-10-15 10:48
Fixed in dad6519fdb453735727da30562b4bdd1a3887414. It seems that when I added the recipe for steam (not that long ago), it had unintended consequences for how I prioritized resources. I've readjusted those priorities, and it should now be working as intended.

**Closed by KirkMcDonald** 2018-10-15 10:48 UTC
