### ISSUE TITLE
Suggestion: Let users pick belt and assembler level for specific rows on the factory tab to override global settings (same way modules work basically)

### ISSUE THREAD

**Issue by nailertn** [KirkMcDonald/kirkmcdonald.github.io#147] opened 2019-04-29 13:01 UTC
Modules allow players to pick a default setting but override individual rows. Making belts, assemblers, furnaces and drills function the same way would be an excellent addition to the versatility of the calculator. A base with only blue belts or only level 2 assemblers rarely reflects a real world scenario, let players fine tune their settings when they need it.

**Comment by KirkMcDonald** [comment] 2019-04-29 15:50
Duplicate of #96.

**Closed by KirkMcDonald** 2019-04-29 15:50 UTC
