### ISSUE TITLE
selecting advanced oil processing still uses basic in calculator

### ISSUE THREAD

**Issue by mathijswesterhof** [KirkMcDonald/kirkmcdonald.github.io#119] opened 2019-01-04 20:23 UTC
as shown in the image below, when setting the option for advanced oil processing in the settings tab the sprite for factories changes but the calculator still uses the basic conversion scheme. the outcome should be 100 -> 10:45:55 (as stated here https://wiki.factorio.com/Oil_processing) 

![image](https://user-images.githubusercontent.com/10096922/50709000-9ab87800-1066-11e9-83d9-c465bc2ad15e.png)

**Comment by KirkMcDonald** [comment] 2019-01-04 22:51
This is working as intended. The issue is that the meaning of the "primary oil processing recipe" is (perhaps) not clearly described. It is possible that the meaning of the option should be changed, or a new option should be added, but I do not consider this a bug.

The idea is that the calculator should find the most efficient use of resources for making a given product. If your only product is heavy oil, then using basic oil processing is more efficient (uses one-third as much oil) than using advanced oil processing. The intent of the option is controlling which level of technology you're at: If you have not yet researched advanced oil processing, then you are limited to basic oil processing, but once you do research it, you will have access to both. (Coal liquefaction is separate from the other two, and the calculator models it by disabling the other two recipes.)

At some point in the future, I may revisit this problem in a more generalized way, as part of supporting mods like Bob's, which have this "Which recipe should I use?" problem for many more items than the vanilla recipe graph does. But for now, I am content with the current behavior, and am closing this issue.

**Closed by KirkMcDonald** 2019-01-04 22:51 UTC
